### ISSUE TITLE
Coverage report for different absolute source file paths on build and test time

### ISSUE THREAD

**Issue by skylock** [cypress-io/code-coverage#77] opened 2019-09-26 13:04 UTC
Sample repo : [https://github.com/skylock/cypress-angular-coverage-example](https://github.com/skylock/cypress-angular-coverage-example)

Steps:
1. Build & Instrument app code & deploy the app
__coverage__ object will contain source-map's absolute path where the app has been instrumented (e.g. codebuild)
e.g. /codebuild/output/src922053178/src/src/app/app.module.ts
2. Run cypress tests using cypress/included:3.4.1 container & mount source branch folder in the container e2e folder

Problem: The code coverage object is extracted to .nyc_output/out.json but the report is not generated

This is because code coverage plugin will expect that the __coverage__ object paths to point to it's absolute path e.g. /e2e/src/app/app.module.ts but the paths are actually  where the app has been instrumented.

Please advice on how to overcome this issue.

**Comment by skylock** [comment] 2019-09-27 10:49
Fix I found:
On the codebuild container that is running the tests within cypress container i updated the source files absolute path to the current working directory and then re-create the coverage report using nyc

      # Fix coverage report paths
      - sed  -i -r "s|([\/].+\/src\/)|$PWD\/src\/|g" .nyc_output/out.json
      # Create new coverage report
      - npx nyc report --report-dir ./coverage --reporter=lcov --reporter=clover --reporter=json

**Comment by jennifer-shehane** [comment] 2019-10-10 17:15
Hey @skylock, since you fixed your issue - was there anything required on our end here? Can you close the issue?

**Comment by skylock** [comment] 2019-10-10 19:07
The coverage plugin works out of the box when ran on local machine but when ran in a cypress docker container will fail the report due to the different paths. Would be nice to work out of the box.

**Comment by jennifer-shehane** [comment] 2019-10-16 16:25
Hey @skylock, if this is a separate issue from the original? Can you open a new issue detailing the problem you are seeing and how to reproduce it? Thanks!

**Closed** 2019-10-24 13:39 UTC
