### ISSUE TITLE
nyc out.json is empty

### ISSUE THREAD

**Issue by nweiser1** [cypress-io/code-coverage#78] opened 2019-09-26 13:40 UTC
vue/node js project running with cypress tests, trying to add coverage
the `nyc_output` folder is there also the `processinto` folder
The `out.json` file is either empty or not created, depending on how i play with the setting files
I also see in the cypress run that the after all task - covergereport runs, but the after each task - combine coverge does not run

my plugins index file has the 
```js
on('task', require('@cypress/code-coverage/task'))
```
my babel
```
"babel": {
    "plugins": ["istanbul"],
    "presets": [
      [
        "@babel/preset-env",
        {
          "modules": "commonjs",
          "targets": {
            "node": "current"
          }
        }
      ]
    ]

nycrc
{
        "extends": "@istanbuljs/nyc-config-babel",
        "extension": [".js", ".vue"],
        "all": true
}
```

my command line
```
nyc --all npm run test:open
```

my json has 
```json
"devDependencies": {
    "@babel/core": "^7.5.0",
    "@babel/preset-env": "^7.5.2",
    "@cypress/code-coverage": "^1.10.1",
    "@vue/cli-plugin-babel": "^3.8.0",
    "@vue/cli-plugin-eslint": "^3.8.0",
    "@vue/cli-plugin-unit-jest": "^3.7.0",
    "@vue/cli-service": "^3.8.0",
    "@vue/eslint-config-standard": "^4.0.0",
    "@vue/test-utils": "^1.0.0-beta.29",
    "axios-mock-adapter": "^1.17.0",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-jest": "^22.4.3",
    "babel-plugin-component": "^1.1.1",
    "babel-plugin-istanbul": "^5.2.0",
    "cypress": "^3.4.1",
    "cypress-failed-log": "^2.5.1",
    "eslint": "^5.16.0",
    "eslint-plugin-cypress": "^2.0.1",
    "eslint-plugin-cypress-dev": "2.1.0",
    "eslint-plugin-jest": "^22.7.2",
    "eslint-plugin-mocha": "5.3.0",
    "eslint-plugin-vue": "^5.0.0",
    "gulp-babel": "^8.0.0",
    "istanbul-lib-coverage": "^2.0.5",
    "jest": "^24.8.0",
    "jest-html-reporter": "^2.5.0",
    "jest-junit": "^6.4.0",
    "jest-transform-stub": "^2.0.0",
    "nodemon": "^1.19.1",
    "nyc": "^14.1.1",
    "sass": "^1.18.0",
    "sass-loader": "^7.1.0",
    "start-server-and-test": "^1.10.0",
    "stylus": "^0.54.5",
    "stylus-loader": "^3.0.1",
    "supertest": "^4.0.2",
    "supertest-as-promised": "^4.0.2",
    "vue-cli-plugin-vuetify": "^0.5.0",
    "vue-jest": "^3.0.4",
    "vue-template-compiler": "^2.6.10",
    "vue-test-utils": "^1.0.0-beta.11",
    "vuetify-loader": "^1.0.5",
    "vuex-mock-store": "0.0.7",
    "wait-on": "^3.3.0"
```
what am i missing?

**Comment by leorigon** [comment] 2019-10-01 17:37
We have the same problem here :(

**Comment by stanleylu3216** [comment] 2019-10-11 08:35
same here.

**Comment by JacekWalczak92** [comment] 2019-10-15 09:54
For me works to add in package.json:
"nyc": {
    "exclude-after-remap": false
  }

**Comment by 3590Duncan** [comment] 2019-10-28 18:24
Also experiencing this issue

**Comment by albertodeago** [comment] 2019-10-30 20:47
same here

**Comment by peterbabic** [comment] 2019-11-09 09:59
Mine is also empty, followed the guide https://docs.cypress.io/guides/tooling/code-coverage.htm step by step until fullstack.

**Comment by ronaiza-cardoso** [comment] 2019-11-11 17:38
same here

**Comment by leorigon** [comment] 2019-11-13 20:21
I fixed this issue on our project (we using TypeScript) re-installing the dependencies and putting these codes:
  
**package.json**
```
"scripts": {
   "cy:run:report": "nyc --reporter=html cypress run"
},
"devDependencies": {
    "@istanbuljs/nyc-config-typescript": "0.1.3",
    "babel-plugin-istanbul": "5.2.0",
    "source-map-support": "0.5.16",
    "@cypress/code-coverage": "1.10.1",
    "istanbul-lib-coverage": "2.0.5",
    "nyc": "14.1.1"
},
"nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "extension": [
      ".tsx"
    ],
    "include": [
      "src/**/*.tsx"
    ],
    "exclude": [
      "cypress/",
      "assets/",
      "test/"
    ],
    "all": true
  }
```
**.babelrc**
```
"plugins": ["istanbul"]
```
added in **plugins/index.js** `module.exports`:

```
on('task', require('@cypress/code-coverage/task'))
```
and **support/index.ts**
```
import '@cypress/code-coverage/support'
```

It's works for now, but I can improve these.

**Comment by bahmutov** [comment] 2019-11-14 20:53
Can I please have a reproducible repo with the problem? Otherwise I have no idea what the possible problems could be

**Comment by elaco77** [comment] 2019-11-21 12:24
@bahmutov here's a repo where you can reproduce the issue. However I run the test, the nyc/out.json remains empty.

Feel free to contribute on the repo if you feel so. Also, let me know if there's anything else I can do.

https://github.com/elaco77/cypress-code-coverage-showcase

**Comment by albertodeago** [comment] 2019-11-22 17:03
Oh god, in my case I missed a babel configuration thing... I forgot to add 
"plugins": ["transform-class-properties", "istanbul"] 
to my babel config

**Comment by rajatsan** [comment] 2019-12-07 12:37
I faced the same issue. Downgrading my ```nyc``` version from ```14.x.x``` to ```13.x.x``` fixed the problem, as mentioned here https://github.com/cypress-io/code-coverage/issues/65.

**Comment by elaco77** [comment] 2019-12-12 13:36
Dear Cypress team, any update on this one?

**Comment by Zaid-Ajaj** [comment] 2020-01-17 15:01
Same issue here

**Comment by harishkrishnan24** [comment] 2020-01-18 06:59
Same issue here... +

**Comment by kbhutiya** [comment] 2020-01-23 20:29
Same issue !

**Comment by HeckCas** [comment] 2020-01-24 17:46
Me and my team are experiencing the same here
👀

We have tried but still did not find what is it for 😅 😬

**Comment by redaxmedia** [comment] 2020-01-27 15:49
I think the empty `out.json` is an hint that the nyc configuration is not set properly. Since nyc >=14 for example, you have to set `"extension": [".ts"]` for typescript. There is a nice preset:

```
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true
  }
```

For those who have issues with Angular, I found a working example that produces the html report on my local machine: https://github.com/skylock/cypress-angular-coverage-example

**Comment by Ozymandias9000** [comment] 2020-01-29 21:55
Same problem.

**Comment by bahmutov** [comment] 2020-02-03 19:49
@elaco77 I have copied your example - you are not instrumenting your code, once you follow https://github.com/cypress-io/instrument-cra or https://github.com/bahmutov/testing-react#installation instructions your source code will be instrumented on the fly, and code coverage will be saved

<img width="904" alt="Screen Shot 2020-02-03 at 2 49 37 PM" src="https://user-images.githubusercontent.com/2212006/73685600-6d3c6480-4694-11ea-8caf-2c03fdbc2f4a.png">

**Comment by bahmutov** [comment] 2020-02-03 20:27
I think what got lost in README is that this plugin DOES NOT instrument your application's code - you have to do this. I added a strong note in https://github.com/cypress-io/code-coverage#instrument-your-application with examples. There are many examples linked from the readme https://github.com/cypress-io/code-coverage#examples to copy instrumentation, so I will close this issue for now. If you still are experiencing an empty coverage object, even if the `window.__coverage__` has the info, please open a new issue with a link to the reproduction.

**Closed by bahmutov** 2020-02-03 20:27 UTC

**Comment by KarimElKhashab** [comment] 2020-07-17 21:14
I'm facing a problem where the window.__coverage__ is always coming "undefined" even after following all the Cypress code coverage documentation steps with various instrumentation options mentioned... and when starting my server with the cmd
```
  "scripts": {
    "start": "PORT=7777 react-app-rewired -r @cypress/instrument-cra start",
}
```
I get the following error

**EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline'** 

Appreciate your help on this @bahmutov

**Comment by ngokevin** [comment] 2022-06-02 00:31
The issue for me was during production build mode, I had to force my plugin to do instrumentation (vite-plugin-istanbul + forceBuildInstrumentation option).

**Comment by giagara** [comment] 2024-02-01 11:08
> The issue for me was during production build mode, I had to force my plugin to do instrumentation (vite-plugin-istanbul + forceBuildInstrumentation option).

how come? i am not able to use code coverage with vite

**Comment by mayursonawale2601** [comment] 2024-03-27 03:41
Thanks, @bahmutov for your valuable comment 🙌 
After multiple trials and errors, I was finally able to generate a code coverage report.

First, I tried everything as per the [cypress code coverage doc](https://docs.cypress.io/guides/tooling/code-coverage) 

Then, I installed the [@cypress/instrument-cra](https://www.npmjs.com/package/@cypress/instrument-cra) package as @bahmutov mentioned in his [comment](https://github.com/cypress-io/code-coverage/issues/78#issuecomment-581587117).
`npm install --save-dev @cypress/instrument-cra`
and update my npm script as `"start": "react-scripts -r @cypress/instrument-cra start",`

I made a lot of changes to multiple files. I hope the following package, and file information will help you all to debug your issues.

**cypress/support/commands.js**
`import '@cypress/code-coverage/support'` // At the top of the file

**.babelrc:** 
```
{
  "plugins": ["istanbul"]
}
```
**package.json:** [package.json](https://github.com/cypress-io/code-coverage/files/14767129/package.json)


**cypress.config.js:** 
```
const { defineConfig } = require('cypress')`
module.exports = defineConfig({
 fixturesFolder: false,
 env: {
    codeCoverage: {
     url: 'http://localhost:3000/__coverage__',
    exclude: 'cypress/**/*.*'
   }
  },
  e2e: {
    setupNodeEvents(on, config) {
      require('@cypress/code-coverage/task')(on, config)
     return config;
    },
  },
})
```

I hope this solution will work for everyone! 🙏
